version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: assignment
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3307:3306"
    networks:
      - spring-net
    volumes:
      - db_data:/var/lib/mysql

  springboot:
    build: .
    container_name: moonrider-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/assignment
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 9999
    ports:
      - "9999:9999"
    networks:
      - spring-net

volumes:
  db_data:

networks:
  spring-net:
